### ISSUE TITLE
Stacktrace dumped if ldm-daily-usage.py is run with a bad configuration file

### ISSUE THREAD

**Issue by markmckeown** [WANdisco/livedata-migrator-scripting#2]
```
# ./ldm-daily-usage.py --config ldm-daily-usage.config
Traceback (most recent call last):
  File "./ldm-daily-usage.py", line 248, in <module>
    sys.exit(main())
  File "./ldm-daily-usage.py", line 237, in main
    config = json.load(f)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 5 column 1 (char 113)
```

If the configuration file is corrupt should not print stack trace, instead an error message should be printed indicating something is wrong with the configuration file. The error should include _Expecting property name: line 5 column 1 (char 113)_

**Comment by markmckeown** [comment]
Should be able to test this without needing to run LiveData Migrator.
